name: Check Spotify Version

on:
  schedule:
    - cron: "0 */1 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run version checker
        run: python main.py

      - name: Commit if version changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Spotify version"
          git push
